apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-html
  namespace: webapp
data:
  index.html: |
    <html>
      <head><title>Welcome</title></head>
      <body>
        <h1>Hello from NGINX after login 🎉</h1>
      </body>
    </html>