apiVersion: apps/v1
kind: Deployment
metadata:
  name: oauth2-proxy
  namespace: webapp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: oauth2-proxy
  template:
    metadata:
      labels:
        app: oauth2-proxy
    spec:
      containers:
        - name: oauth2-proxy
          image: quay.io/oauth2-proxy/oauth2-proxy:v7.2.1
          args:
            - --provider=github
            - --email-domain=*
            - --upstream=http://nginx.webapp.svc.cluster.local:80
            - --cookie-secret=$(OAUTH2_PROXY_COOKIE_SECRET)
            - --client-id=$(OAUTH2_PROXY_CLIENT_ID)
            - --client-secret=$(OAUTH2_PROXY_CLIENT_SECRET)
            - --http-address=0.0.0.0:4180
            - --redirect-url=https://verbose-space-zebra-6pj46ppq9643rg7g-8080.app.github.dev/oauth2/callback

            - --cookie-secure=false
          envFrom:
            - secretRef:
                name: oauth2-proxy-secret
          ports:
            - containerPort: 4180
