apiVersion: v1
kind: Service
metadata:
  name: nginx
  namespace: webapp
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 80
  selector:
    app: nginx
