apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-config
  namespace: nginx-auth
data:
  default.conf: |
    server {
        listen 80;
        location / {
            root /usr/share/nginx/html;
            index index.html index.htm;
        }
    }
