apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-auth
  namespace: nginx-auth
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx-auth
  template:
    metadata:
      labels:
        app: nginx-auth
    spec:
      containers:
        - name: nginx
          image: nginx:alpine
          ports:
            - containerPort: 80
          volumeMounts:
            - name: nginx-config
              mountPath: /etc/nginx/conf.d
        - name: oauth2-proxy
          image: quay.io/oauth2-proxy/oauth2-proxy:v7.6.0
          args:
            - --provider=github
            - --http-address=0.0.0.0:4180
            - --upstream=http://127.0.0.1:80/
            - --cookie-secret=$(OAUTH2_PROXY_COOKIE_SECRET)
            - --client-id=$(OAUTH2_PROXY_CLIENT_ID)
            - --client-secret=$(OAUTH2_PROXY_CLIENT_SECRET)
            - --cookie-secure=false
            - --redirect-url=http://127.0.0.1:8080/oauth2/callback
            - --email-domain=*  
          envFrom:
            - secretRef:
                name: nginx-oauth2-secret
          ports:
            - containerPort: 4180
      volumes:
        - name: nginx-config
          configMap:
            name: nginx-config
---
apiVersion: v1
kind: Service
metadata:
  name: nginx-auth-service
  namespace: nginx-auth
spec:
  type: NodePort
  selector:
    app: nginx-auth
  ports:
    - name: oauth2
      port: 80
      targetPort: 4180
      nodePort: 30080