apiVersion: apps/v1
kind: Deployment
metadata:
  name: webapp
spec:
  replicas: {{ .Values.webapp.replicas }}
  selector:
    matchLabels:
      app: web
  template:
    metadata:
      labels:
        app: web
    spec:
      containers:
        - name: web
          image: {{ .Values.webapp.image }}
          ports:
            - containerPort: {{ .Values.webapp.port }}
---
apiVersion: v1
kind: Service
metadata:
  name: webapp
spec:
  selector:
    app: web
  ports:
    - protocol: TCP
      port: 80
      targetPort: {{ .Values.webapp.port }}
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: oauth2-proxy
spec:
  replicas: {{ .Values.oauth2Proxy.replicas }}
  selector:
    matchLabels:
      app: oauth2-proxy
  template:
    metadata:
      labels:
        app: oauth2-proxy
    spec:
      containers:
        - name: oauth2-proxy
          image: {{ .Values.oauth2Proxy.image }}
          args:
            - --provider=github
            - --http-address=0.0.0.0:4180
            - --upstream=http://nginx-service.webapp.svc.cluster.local
            - --cookie-secret=$(OAUTH2_PROXY_COOKIE_SECRET)
            - --cookie-secure=false
            - --client-id=$(OAUTH2_PROXY_CLIENT_ID)
            - --client-secret=$(OAUTH2_PROXY_CLIENT_SECRET)
            - --redirect-url={{ .Values.oauth2Proxy.redirectUrl }}
            - --email-domain=*
          env:
            - name: OAUTH2_PROXY_CLIENT_ID
              valueFrom:
                secretKeyRef:
                  name: oauth2-secret
                  key: client-id
            - name: OAUTH2_PROXY_CLIENT_SECRET
              valueFrom:
                secretKeyRef:
                  name: oauth2-secret
                  key: client-secret
            - name: OAUTH2_PROXY_COOKIE_SECRET
              valueFrom:
                secretKeyRef:
                  name: oauth2-secret
                  key: cookie-secret
          ports:
            - containerPort: 4180
---
apiVersion: v1
kind: Service
metadata:
  name: oauth2-proxy
spec:
  selector:
    app: oauth2-proxy
  ports:
    - protocol: TCP
      port: 4180
      targetPort: 4180
      nodePort: {{ .Values.oauth2Proxy.nodePort }}
  type: NodePort